### ISSUE TITLE
Težave s povezovanjem Postgres-a in Rstudia

### ISSUE THREAD

**Issue by nezahabjan** [anamkravanja/Filmi#2]
Pozdravljeni, 

prosili bi Vas za pomoč pri povezavi med Postgres-om in Rstudiem, v datoteki sql.R. Tabele se ustvarijo a se podatki v njih ne prikažejo, pač pa ostanejo prazne.

Najlepša hvala že vnaprej, lep pozdrav,
Neža Habjan

**Comment by jaanos** [comment]
Kolikor vidim, imate v funkciji `insert_data` pri klicih funkcije `dbWriteTable` na koncu odvečen parameter `con = conn`. Če tega odstranite, bi moralo delovati.

**Comment by anamkravanja** [comment]
To sem že poskusila. Vendar mi vedno javi sledečo napako : 
Error: `con` must not be NULL 

Potem sem videla sledeče : https://github.com/timotejvesel/vojne/issues/1 

Zato sem tisto dodala na koncu. Potem je delovalo, a podatki se še vedno niso naložili na PostgreSQL.
