### ISSUE TITLE
težave pri projektu

### ISSUE THREAD

**Issue by anamavsenik** [anamkravanja/Filmi#3]
Pozdravljeni,

prosili bi Vas za pomoč. Imamo težave s projektom, saj nam, ker imamo podatke zaradi velikosti vsak na svojem računalniku, program javlja različne napake in smo se nekako zgubili v tem. V bistvu je naša naloga sedaj vse skupaj povezati. Imamo narejeno shiny za prijavo in imamo shiny kako naj naša spletna stran izgleda. Prav tako imamo tabele na Postgresu. Prijavo moramo tudi povezati z tabelo za uporabnike.  Nekako ne vemo kako se lotiti vsega skupaj.  Bi nam lahko povedali kaj naj se lotimo najprej in približno na kakšen način.

Najlepša hvala že vnaprej, lep pozdrav,
Ana M. Kravanja

**Comment by jaanos** [comment]
Najprej, pazite na velikost črk pri navajanju imen datotek - programi, ki jih kličete na začetku `server.R`, imajo končnico `.R` (velika črka!), zato jih kot take tudi navajajte.

Kolikor vidim, imate trenutno tabelo `uporabniki` s stolpcem `geslo`, medtem ko koda v `serverFunctions.R` pričakuje, da bo (zgoščeno) geslo shranjeno v stolpcu `hash` - tako bo treba popraviti bodisi v bazi, bodisi v kodi. Prav tako se v kodi včasih uporablja spremenljivka `uporabnikID`, včasih pa `uporabnikiID` - to bo treba poenotiti. Uporabniku `javnost` bo treba seveda dati še ustrezne pravice pisanja v bazo - zagotovo potrebuje pravico `INSERT` na tabelah `uporabniki` in `ocena` (da se bo uporabnik lahko vpisal in dodajal ocene), če pa želite v aplikaciji imeti še administracijo, bo treba seveda nastaviti ustrezne pravice še na ostale tabele.

Mimogrede, vidim, da aplikacija trenutno uporablja bazo `banka2019_anamarijak`, kjer imate tudi tabele iz vaj. Da se to ne bo mešalo, svetujem, da raje uporabite bazo npr. `sem2019_anamarijak`. Glede na to, da imate podatke že uvožene, lahko v phppgadminu obstoječe tabele enostavno izvozite (zavihek *Export* pri pregledu tabele) in jih nato uvozite v drugo bazo (kot stavke SQL).

Še to: v veznih tabelah (`ima`, `nastopa`, `nosilec`) trenutno nimate glavnega ključa - ta naj sestoji kar iz obeh stolpcev skupaj. V tabeli `ocena` naj bo `uporabnik_id` referenca na tabelo `uporabniki`, v slednji tabeli pa naj ima stolpec `username` še lastnost `UNIQUE`, da se uporabniška imena ne bodo ponavljala.

**Comment by nezahabjan** [comment]
Najlepša hvala, delamo na popravkih, ki ste jih navedli. Še vedno pa imamo največjo povezavo nasploh s povezavo z bazo. Najpogostejša napaka, ki jo javi program je nekaj takega: " RS-DBI driver: (could not connect javnost@baza.fmf.uni-lj.si:5432 on dbname "sem2019_anamarijak": could not translate host name "baza.fmf.uni-lj.si" to address: Unknown server error ".
Prosili bi vas za nasvet, saj ne vemo kako napako odpraviti.

Najlepša hvala, lep pozdrav,
Neža Habjan

**Comment by anamavsenik** [comment]
Sedaj smo odpravili nekatere napake, ki ste nam jih napisali, na nekaterih še delamo. Vendar nam že pri prevajanju tabel vrže napako:
 Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near ")"
LINE 4:                                              )
                                                     ^
) 

Prav tako me zanima, kako bodo drugi uporabniki imeli datoteko auth.R, ki je potrebna pri sql datoteki, če je ne dodam na github. Ali jo moram najprej dodati da jo dobita onedva, potem pa napisati v datoteko gitignor, da ne bo vidna na gitu?


Hvala za odgovor.

**Comment by jaanos** [comment]
Napaka se pojavi, ker imate nekje napako v stavku SQL - kot vidim, imate pri ustvarjanju tabel `nastopa`, `nosilec` in `ima` odvečne vejice pred zadnjim zaklepajem (kot rečeno, v teh tabelah dodajte še glavni ključ).

Datoteka `auth.R` je namenjena samo vam, da ustvarite bazo in napolnite tabele. Ker je trenutno na repozitoriju, je s tem geslo za vekomaj objavljeno na internetu - svetujem torej, da ga @anamkravanja zamenjaš, `auth.R` pa dodaste nazaj v `.gitignore` in jo pobrišete iz repozitorija. Datoteko (z novim geslom) si potem izmenjate zasebno, npr. po e-pošti. V `server.R` potem seveda uporabite `auth_public.R`, pri čemer mora uporabnik `javnost` imeti ustrezne pravice (kot vidim, je to že upoštevano v `sql.R`, ni pa še aplicirano na bazi).

Še to: da bo mogoče aplikacijo pognati, bo treba tudi v `ui.R` vključiti `libraries.R`.
