### ISSUE TITLE
Zaključevanje s projektom

### ISSUE THREAD

**Issue by anamavsenik** [anamkravanja/Filmi#4]
Pozdravljeni!

Pri projektu smo naredili, kar smo nameravali. Sedaj delamo le še na estetskih popravkih. Bi nam lahko svetovali, ali naj še kaj spremenimo pri sami spletni strani, bazi ali kje drugje?

Hvala za odgovor in lep pozdrav,
Ana Marija Kravanja

**Comment by jaanos** [comment]
Najprej, kot sem omenil v #3, poskrbite za dostop z uporabnikom `javnost` (datoteka `auth_public.R`) ter pobrišite `auth.R` in zamenjajte geslo.

Kolikor vidim, imate v bazi pri nagradah ponovljene podatke. Trenutno imate tri tabele - `nagrada`, `dobi` in `nosilec`. V tabeli `nagrada` je stolpec `ime` odveč, saj gre za ime filma ali osebe, ki ga lahko dobite po ustreznem ID-ju; prav tako je odveč stolpec `zmaga`, saj ima povsod isto vrednost. Glede na to, da sta samo dve vrstici taki, da imata tako ID osebe kot filma (pa še tukaj gre najverjetneje za napako), bi svetoval, da stolpca `leto_nagrade` in `kategorija` prestavite v tabeli `dobi` in `nosilec` (tako sta to tabeli nagrad filmov in nagrad igralcev - lahko ju ustrezno preimenujete), tabelo `nagrada` pa pobrišete.

Aplikacije trenutno ne morem pognati, saj se v `ui.R` sklicujete na neobstoječo spremenljivko `film` - če želite podatke o najstarejšem in najnovejšem filmu dobiti iz baze, si poglejte npr. [tukaj](https://github.com/zigakodric/Letalski-prevozniki/blob/2dec1711612558c745b906296e29d59f43897075/server.R#L21-L32), kako posodobiti izbirnik.

Pri iskanju po naslovu filma ne izpišete nič, če film ni bil posnet po knjigi. Namesto ene poizvedbe, ki vrne vse podatke (zaradi `JOIN`ov se ti tudi ponavljajo), raje naredite več poizvedb - eno za osnovne podatke, eno za knjige, in eno za igralce. Svetujem tudi, da namesto tega, da daste na izbiro vse filme, iščete po delu vnesenega niza (uporabite `LIKE`) ter za najdene filme izpišete osnovne podatke. Podobno lahko naredite tudi pri igralcih.

Lepo bi bilo, če bi lahko pri izpisu filmov lahko kliknili na posamezen film in tam prikazali vse podatke o njem - potem pri samem iskanju ne bi bilo treba prikazovati knjig in igralcev, prav tako pa bi lahko ocenjevanje lahko naredili na tej strani. Pri vnosu ocene lahko s pomočjo ukaza [`shinyjs::reset`](https://github.com/timotejvesel/vojne/blob/15ee8396ce101828a00e430d01a97f2a4fc178c7/shiny/server.R#L265) poskrbite, da se posodobi seznam ocen.

**Comment by anamavsenik** [comment]
Pozdravljeni!

Popravili in spremenili smo nekatere stvari v programu, sedaj je tak, kot smo si zamislili.  Zanima nas, ali bi bilo dobro še kaj popraviti. Oziroma če je v redu za oddajo?

Najlepša hvala in lep pozdrav,
Ana Marija K.

**Comment by jaanos** [comment]
Aplikacije še vedno ne morem pognati - problem je tukaj:
https://github.com/anamkravanja/Filmi/blob/ffdb7c3beeb5be4874bbd71bac5920b6927c23ad/shiny/ui.R#L116
Posodobitev vrednosti lahko naredite kar v istem `observe` kot za drsnik `leto`.

Sicer pa še vedno veljajo zgornji komentarji glede organizacije tabel ter iskanja po naslovu filma in igralcih. Opažam še, da se pri iskanju po letu izida vsak film izpiše enkrat za vsak žanr. Namesto tega raje uporabite funkcijo [`string_agg`](https://www.postgresql.org/docs/9.1/functions-aggregate.html), s katero lahko žanre združite v en sam niz, tako da bo vsakemu filmu ustrezala samo ena vrstica.

**Comment by anamavsenik** [comment]
Ne razumem zakaj nam aplikacija deluje. Hvala. Bomo popravili.

**Comment by jaanos** [comment]
Kot rečeno, se sklicujete na spremenljivko `film`, ki pa ni nikjer definirana.

**Comment by nezahabjan** [comment]
Pozdravljeni,

pri projektu smo popravili, kar ste naročili, imamo le še en problem. Ko zaženemo server.r se namreč program ne zažene, če prej ne zaženemo tudi sql.r. Zanima nas ali je to v redu in če ni, kako lahko stvar popravimo?

Najlepša hvala že vnaprej,
Lp, Neža

**Comment by jaanos** [comment]
Pri meni se aplikacija zažene, če jo poženem takoj po nalaganju projekta. Kakšno napako pa dobite?

Imam še sledeče pripombe:
* Filmov je v resnici preveč, da bi jih imeli vse naštete v izbirniku (kar se vidi pri ocenjevanju, saj se zadnji film v seznamu začne na *A*). Zato bo bolje, če pri iskanju naredite tako kot pri iskanju igralcev; pri ocenjevanju pa lahko poleg vnosnega polja pustite še izbirnik, kjer se pa prikažejo le tisti filmi, ki ustrezajo vnesenemu nizu (zraven lahko daste še letnico, da bo filme mogoče ločiti).
* Za izpisovanje besedila namesto `renderPrint` raje uporabite `renderText`.
* Iskanje nagrad ne deluje - pri iskanju bo treba pridružiti še tabelo `nagrada` (ali pa naredite tako, kot sem napisal zgoraj).

**Comment by sdekanovic** [comment]
Pozdravljeni, 

napaka, ki jo dobimo:
Warning: Error in postgresqlNewConnection: RS-DBI driver: (could not connect javnost@baza.fmf.uni-lj.si:5432 on dbname "sem2019_anamarijak": could not translate host name "baza.fmf.uni-lj.si" to address: Unknown server error

Lep pozdrav,
Stefan

**Comment by jaanos** [comment]
Do takšne napake pride, če ni povezave z internetom (ali iz kakšnega drugega razloga imenski strežnik ni dosegljiv). Je to edina napaka? Ali se to dogaja na več računalnikih, morda celo na več lokacijah?

**Comment by sdekanovic** [comment]
Pozdravljeni!

To je edina napaka, ki jo dobiva jaz in Neža vsak na svojem računalniku. Pri meni se to zgodi nekako takole: če najprej poženem sql.r potem pa server.r, mi aplikacijo zažene. Če pa najprej poženem server.r, dobim to napako. V tem sessionu mi potem vrže isto napako, če probam zagnati sql.r.

Je mogoče kaj narobe z ' source("lib/libraries.R") '? Saj sem opazil, da ko ta del prestavim v sql.r, mi vrže to napako, tudi ko najprej poženem sql.r.

Lep pozdrav

**Comment by jaanos** [comment]
Nisem prepričan, kaj se dogaja. Če ste na FMF, se lahko oglasite, pa pogledamo. Prosim javite, če in kdaj bi se oglasili, ker imam še druge opravke (bom pa v bližini).

**Comment by anamavsenik** [comment]
Imate mogoce cas dopoldan v ponedeljek? Oziroma zjutraj? Ob kateri uri lahko pridemo?

**Comment by jaanos** [comment]
Predlagam, da pridete v ponedeljek ob 10h.

**Comment by nezahabjan** [comment]
Pozdravljeni,

aplikacija nam sedaj lepo deluje in dodali smo še zadnjo stvar pri projektu, pri zavihku komentiranje. Zanima nas, če se lahko dogovorimo s profesorjem Orbaničem za zagovor?

Lp, Neža

**Comment by jaanos** [comment]
V redu, bom dodal povezavo na repozitorij predmeta, tako da se lahko z @alenFMF domenite za termin zagovora. Če boste do takrat še kaj spreminjali, mi javite, da posodobim povezavo.

**Comment by nezahabjan** [comment]
V redu, najlepša hvala, bomo sporočili.

Lep pozdrav, Neža

**Comment by anamavsenik** [comment]
Prosim, če pred jutrišnjim zagovorom še enkrat posodobite povezavo. Najlepša hvala.

**Comment by jaanos** [comment]
Sem posodobil.
